In [10]:
import numpy as np
import pylab as pl
from sklearn.neighbors import KNeighborsClassifier as KNN

with open("madelon_train.data", "r") as f:
    X = np.fromstring(f.read(), dtype=int, sep=" ").reshape((2000, 500))
print(X)

# clf = KNN(n_neighbors=3)
# clf.fit(X, y) #обучение
# print(clf)

[[485 477 537 ... 479 475 496]
 [483 458 460 ... 492 510 517]
 [487 542 499 ... 489 499 498]
 ...
 [480 517 631 ... 500 523 481]
 [484 481 505 ... 473 527 485]
 [474 493 469 ... 489 516 516]]
