In [118]:
import numpy as np
import pylab as pl
from sklearn.neighbors import KNeighborsClassifier as KNN

with open("madelon_train.data", "r") as f:
    X = np.fromstring(f.read(), dtype=int, sep=" ").reshape((2000, 500))
print(X)

with open("madelon_train.labels", "r") as f:
    y = np.fromstring(f.read(), dtype=int, sep=" ").reshape((2000,))
print(y)

clf = KNN(n_neighbors=15)
clf.fit(X, y) #обучение
print(clf)

[[485 477 537 ... 479 475 496]
 [483 458 460 ... 492 510 517]
 [487 542 499 ... 489 499 498]
 ...
 [480 517 631 ... 500 523 481]
 [484 481 505 ... 473 527 485]
 [474 493 469 ... 489 516 516]]
[-1 -1 -1 ... -1  1  1]
KNeighborsClassifier(n_neighbors=15)


In [134]:
a = 100 * np.random.rand(1)
c = a[0] * np.random.rand(500,)
# print(c)
clf.predict([c])
clf.predict_proba([c])

array([[0.53333333, 0.46666667]])

In [137]:
with open("madelon_valid.data", "r") as f:
    valid = np.fromstring(f.read(), dtype=int, sep=" ").reshape((600, 500))
# print(valid)

with open("madelon_valid.labels", "r") as f:
    labels = np.fromstring(f.read(), dtype=int, sep=" ").reshape((600,))
# print(labels)

# clf.predict(valid)
labels - clf.predict(valid)

array([ 0,  0, -2,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2,  0, -2,
        0, -2,  2,  0,  0,  2,  0,  0,  2,  0,  0,  0,  2,  2,  0,  0,  0,
        0,  0,  2,  0,  0,  0,  0, -2,  0,  0, -2,  2,  2,  0,  2,  0,  2,
        0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,
        2,  2,  0,  2,  0,  0,  0, -2,  0,  0,  0, -2,  2,  0,  0,  0,  2,
       -2,  2,  0,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0, -2,  0,  0,  0,
        0,  0,  0,  0, -2, -2,  0,  0,  0,  0, -2,  0,  2,  0,  0,  0,  0,
       -2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0, -2,  2,  0, -2,  0,
        0,  0, -2,  0,  0, -2,  2,  0,  0,  0,  2,  0,  2,  0,  0,  2,  0,
        0,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  2,
        0,  0,  0,  2, -2